{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "agledger.fullname" . }}-api
  labels:
    {{- include "agledger.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  unhealthyPodEvictionPolicy: {{ .Values.pdb.unhealthyPodEvictionPolicy | default "AlwaysAllow" }}
  selector:
    matchLabels:
      {{- include "agledger.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
